# pandas자료구조

zz

In [23]:
import pandas as pd
import numpy as np
#from pandas import Series,
# series 는 1차원 dataframe은 2차원 index는 색인

## 1.Series

* 특성상 인덱스가 시각화 되어있음

In [8]:
obj = pd.Series([4, 7, -5, 3])
obj  

0    4
1    7
2   -5
3    3
dtype: int64

In [9]:
obj.values #딕셔너리처럼 values를 따로 받을 수 있다.

array([ 4,  7, -5,  3], dtype=int64)

In [10]:
obj.index #키정도는 아니지만 index를 쓰면 index의 범위를 보여준다. range(0, 4, 1)와 유사한 형태이다. 같지는 않다. rangeindex이기 때문

RangeIndex(start=0, stop=4, step=1)

In [11]:
type(obj.index)

pandas.core.indexes.range.RangeIndex

In [14]:
type(obj.values) #자동 넘파이로 된다.

numpy.ndarray

In [13]:
type(obj)

pandas.core.series.Series

In [16]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2 #이런식으로 인덱스를 사용자 지정가능

d    4
b    7
a   -5
c    3
dtype: int64

In [17]:
obj2.index #이때는 rangeindex가 아닌 리스트형 인덱스다.

Index(['d', 'b', 'a', 'c'], dtype='object')

In [19]:
type(obj2.index) #이때는 그대로 index가 나온다 not range index

pandas.core.indexes.base.Index

In [20]:
obj2.values

array([ 4,  7, -5,  3], dtype=int64)

In [21]:
type(obj2.values)

numpy.ndarray

In [24]:
a = np.array([1, 2, 3, 4])
a[0]

1

In [25]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [26]:
obj[0] #일반 색인과 비슷함.

4

In [28]:
obj2['d']  #이거는 특정 인덱스를 입력해야함.

4

In [30]:
obj2['a']

-5

In [33]:
obj2['d'] = 6
obj2 #값 지정도 가능! 일반 인덱스랑 같다고 생각하자.

d    6
b    7
a   -5
c    3
dtype: int64

In [35]:
obj2[['c', 'a', 'd']] #np의 특성을 그대로 갖고 있다.

c    3
a   -5
d    6
dtype: int64

In [36]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [37]:
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [38]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [39]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [40]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [ ]:
e^6, e^7, e^-5, e^3

In [41]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [42]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [43]:
'b' in obj2

True

In [44]:
'e' in obj2

False

In [46]:
sdata = {'Ohio' : 35000, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}

In [47]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [49]:
states = ['Califonia', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states) #이런식으로 아무리 딕셔너리라도 우선순위는 Series에서의 index를 지정한 것이 우선순위다.
obj4 #그리고 기존에 있던 sdata에서 index와 동일한 key를 가졌으면 해당 value를 가져온다.

Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
dtype: float64

In [50]:
pd.isnull(obj4) #null값이 있는지 알려줌 NULL이면 TRUE 이외에도 결측치를 처리할 함수들이 많다.

Califonia     True
Ohio         False
Oregon       False
Texas        False
dtype: bool

In [51]:
pd.notnull(obj4) # ~isnull

Califonia    False
Ohio          True
Oregon        True
Texas         True
dtype: bool

In [52]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [53]:
obj4

Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
dtype: float64

In [54]:
obj3 + obj4 #양쪽에 둘 다 index가 없으면 연산자체가 성립이 안되서 각자에게 값이 있더라도 NaN값이 나온다.

Califonia         NaN
Ohio          70000.0
Oregon        32000.0
Texas        142000.0
Utah              NaN
dtype: float64

In [57]:
obj4.name = 'population'
obj4
# 이런식으로 series의 명칭을 지정해줄 수 있다.

state
Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
Name: population, dtype: float64

In [58]:
obj4.index.name = 'state'
obj4
#index의 명칭이다.

state
Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
Name: population, dtype: float64

In [59]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [60]:
obj.index = ['BOb', 'Steve', 'Jeff', 'Ryan']
obj #이런식으로 인덱스 재지정도 가능하다 모든 인덱스의 개수와 바꿀 인덱스의 개수가 무조건 같아야만 가능하다

BOb      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## 2.DataFrame

In [95]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame #state는 index가 아니다. 데이터 베이스 형식이라고 생각하자. 각각의 키값이 column이 된다

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [65]:
frame.index #index는 좌측에 있는 행 count가 index다.

RangeIndex(start=0, stop=6, step=1)

In [66]:
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [67]:
frame.values

array([['Ohio', 2000, 1.5],
       ['Ohio', 2001, 1.7],
       ['Ohio', 2002, 3.6],
       ['Nevada', 2001, 2.4],
       ['Nevada', 2002, 2.9],
       ['Nevada', 2003, 3.2]], dtype=object)

In [68]:
type(frame.values) #이것도 ndarray다 결국.

numpy.ndarray

In [72]:
frame.head() #default = 5 지정할 수도 있다.

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [73]:
pd.DataFrame(data, columns=['year', 'state', 'pop']) # columns를 지정하면 위치도 순서에 맞게 지정해준다

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [74]:
pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt']) #series처럼 값이 없으면 NaN이다.

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [97]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
             index = ['one', 'two', 'three', 'four', 'five', 'six'])
frame2 #index가 주어진 리스트에 맞게 반영된다.

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [78]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [79]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [80]:
frame2['state'] # index랑 'state' 컬럼의 값이 나온다.
# dataframe을 색인하면 한차원이 벗겨져서 series가나온다.

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [81]:
type(frame2['state'])

pandas.core.series.Series

In [82]:
frame2.state #괄호가 안붙고 속성으로 사용가능문제는 띄어쓰기가 있는 경우에 못쓰므로 왠만해서 바로 쓰자.

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [83]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [84]:
frame2.one #행색인은 이렇게 안된다.

AttributeError: 'DataFrame' object has no attribute 'one'

In [85]:
frame2.loc['one'] #이런 식으로 써야 한다,.

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object

In [86]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [87]:
frame2['debt'] = 16.5 #일괄적용된다.
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [88]:
frame2['debt'] = np.arange(6.) #이런식으로 np.arange로 6개를 추출해서 넣기 가능 #개수가 같거나 하나여야 한다.
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [89]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five']) #이런식으로 index가 같으면 해당하는  index에 들어가기때문에 잘 들어간다.
val #1차원데이터

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [99]:
frame2['debt'] = val #index 값을 맞춰줬기에 해당 index에 바로 들어가기때문에 값이 잘 들어간다.
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [100]:
frame2.state =='Ohio'

one       True
two       True
three     True
four     False
five     False
six      False
Name: state, dtype: bool

In [101]:
frame2['eastern'] = frame2.state == 'Ohio' #이런식으로 불리언 값도 넣을 수 있다.
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [102]:
del frame2['eastern']
frame2.columns #지워졌다.

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [105]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}} 
frame3 = pd.DataFrame(pop) #내부 딕셔너리의 key 값이 인덱스로 들어간다.
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [106]:
frame3.T #np랑 같음.

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [107]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [108]:
frame3['Ohio'][:2]

2001    1.7
2002    3.6
Name: Ohio, dtype: float64

In [109]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada' : frame3['Nevada'][:2]}
pd.DataFrame(pdata) #이런식으로 시리즈가 들어가도된다. 시리즈의 인덱스를 그대로 가져온다.

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [110]:
frame3.name = 'population'
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [112]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3 #이런식으로 인덱스와 커럼의 이름을 지정하면 시각화도 된다.

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [113]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [114]:
frame3.values.dtype

dtype('float64')

In [115]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [116]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [120]:
frame2.columns.dtype #'O'는 Object라는 말임

dtype('O')

## 3.index

In [124]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [125]:
index[1:]

Index(['b', 'c'], dtype='object')

In [127]:
index[1] = 'd' #이건 안된다.

TypeError: Index does not support mutable operations

In [ ]:
pd.Series
pd.Datafrmae
pd.Index()

In [129]:
labels = pd.Index(np.arange(3)) #Index에서 대분자 조심! i 대문자로 해야함
labels

Int64Index([0, 1, 2], dtype='int64')

In [131]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels) #원래도 같은 값인데 넣어도 된다.
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [133]:
obj2.index is labels #lables에서 index를 할당 받았기에 같은지 확인결과 True

True

In [134]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [135]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [137]:
'Ohio' in frame3.columns

True

In [138]:
2003 in frame3.index

False

In [140]:
pd.Index(['foo', 'foo', 'bar', 'bar'])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 실습

* 딕셔너리 -> 시리즈 변환 (index, values 출력)

In [144]:
dict_data = {'a' : 1, 'b' : 2, 'c' : 3}

data = pd.Series(dict_data)

index = data.index
index

values = data.values
values

* 리스트 -> 시리즈 변환(index, values 출력)

* 튜플 -> 시리즈 변환 (index 설정)

In [173]:
tup_data = ('영인', '2010-05-01', '여', True)
index_name = ['이름', '생년월일', '성별', '학생여부']

data2 = pd.Series(tup_data, index=index_name)
data2

* 시리즈 원소 선택

In [179]:
tup_data = ('영인', '2010-05-01', '여', True)
index_name = ['이름', '생년월일', '성별', '학생여부']

# '영인' 값 가져오기

data = pd.Series(tup_data, index=index_name)
print(data[0])
print(data['이름'])
# 색인을 통해 '생년월일'과 '성별' 선택하기
print(data[['생년월일', '성별']])

영인
영인
생년월일    2010-05-01
성별               여
dtype: object


* 딕셔너리를 데이터 프레임으로 변환

In [181]:
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

In [183]:
dict_dataFrame = pd.DataFrame(dict_data)
dict_dataFrame

c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

* 행 인덱스 / 열 이름 설정

In [189]:
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']], index = ['준서','예은'], columns=['나이', '성별', '학교'])
df

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [190]:
df.index=['학생1', '학생2']
df

나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [192]:
df.columns=['연령', '남녀', '소속']
df

연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

* 나이 ,성별, 학교 -> 연령, 남녀, 소속

In [196]:
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']], index = ['준서','예은'], columns=['나이', '성별', '학교'])
df

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

### rename

In [197]:
df.rename(columns = {'나이': '연령', '성별' : '남녀', '학교': '소속'}) #이런식으로 해도되는데 이때 좋은 건 개수가 일치할 필요없이 원하는 것만 바꾸면 된다.

연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [198]:
df.rename(index = {'준서' : '학생1', '예은' : '학생2'}) #원본은 반영이 안된다. 하고싶으면 , inplace+True를 붙이면 된다!

나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [200]:
df.rename(index = {'준서' : '학생1', '예은' : '학생2'}, inplace=True)

In [ ]:
df

# 중요한 기능들

* 1.재색인

In [202]:
obj = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [204]:
obj2 = obj.reindex(['a', 'b', 'c','d', 'e'])
obj2

a   -5.0
b    7.0
c    3.0
d    4.0
e    NaN
dtype: float64

In [207]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [209]:
obj3.reindex(range(6)) #원래 있던 인덱스를 해당 인덱스의 위치로 재지정

0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
dtype: object

In [212]:
#obj3.reindex(range(6), method=방법)
obj3.reindex(range(6), method='ffill') #채워줬음 1에 0 3에 2 5에 4값이 각각 들어갔다.

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [214]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [215]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [216]:
frame.reindex(['a', 'b', 'c', 'd']) #b는 원래 없었음 그건 NaN으로 처리

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [219]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns = states)  #index뿐만아니라 columns도 index형식을 따르기에 reindex에 사용 가능

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [227]:
frame.loc[['a','c','d']]

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [ ]:
frame.loc[['a','b', 'c','d']]#없는 거 넣으면 안됨

In [ ]:
frame.loc[['a','b', 'c','d']]

## 2.로우나 컬럽 삭제하기

In [228]:
obj = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [231]:
obj.drop('c') # 현장반영 x inplace옵션을 통해서 바꿀 수 있다.

a    0
b    1
d    3
e    4
dtype: int32

In [230]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [232]:
obj.drop(['d', 'c'])

a    0
b    1
e    4
dtype: int32

In [236]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
             index = ['Ohio', 'Colorado', 'Utah', 'New York'],
             columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [237]:
data.drop('Colorado')

one  two  three  four
Ohio        0    1      2     3
Utah        8    9     10    11
New York   12   13     14    15

In [242]:
data.drop(['Colorado', 'Ohio'], axis='index') #두개부턴 리스트를 넣기. #판다스는 axis가 0으로 행이 디폴트

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [244]:
data.drop('two', axis=1) #컬럼이 아닌 index를 바라보기에 axis를 1로 해줘야한다.

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [243]:
data.drop(['two','four'], axis='columns') # or axis=1    axis=0 or index

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [249]:
obj

a    0
b    1
d    3
e    4
dtype: int32

In [251]:
obj.drop('a', inplace=True) # 이건 1차원이라 axis가 의미 없다.
obj

b    1
d    3
e    4
dtype: int32

* 축에대해 연산을 할 때

일반적으로 해당 '축을 따라서' 연산. np에서는 default가 전부라서 지정 안하면 모든 행과 열에 대하여이고 pd에서는 axis의 default가 행인 0이다
축은 중요하다!
삭제하는 경우에는 '그 축을' 삭제

In [ ]:
df.sum
df.mean
df.min
df.max

### 3. 색인하기, 선택하기, 거르기

In [263]:
obj = pd.Series(np.arange(4.), index=['a', 'b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [264]:
obj['b']

1.0

In [265]:
obj[1]

1.0

In [266]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [267]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [268]:
obj < 2

a     True
b     True
c    False
d    False
dtype: bool

In [269]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [270]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [271]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [273]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
            index = ['Ohio', 'Colorado', 'Utah', 'New York'],
            columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [275]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [278]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [281]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [283]:
data[data['three'] > 5] #불리언 색인

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [284]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [287]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

* loc, iloc 선택하기

In [288]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [290]:
data.loc['Colorado'] #loc로 색인

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int32

In [291]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [293]:
data.iloc[1, [1, 2]] #iloc는 숫자로 색인.

two      5
three    6
Name: Colorado, dtype: int32

In [294]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [295]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [296]:
data.loc['Utah']

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [297]:
data.loc[:'Utah', 'two'] #이름 색인은 해당 인덱스를 포함한다.

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [298]:
data.iloc[:, :3] #숫자에는 파이썬 기존 처럼 max가 포함 안된다.

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [300]:
data.three > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [304]:
data.iloc[:,:3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

## 슬라이싱과 불리언 색인은 axis기본이 0이다 행기준

In [306]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [309]:
ser[:1]

0    0.0
dtype: float64

In [312]:
ser.loc[:1] #이 loc는 라벨 색인이라 1까지임.

0    0.0
1    1.0
dtype: float64

In [313]:
ser.iloc[:1]

0    0.0
dtype: float64

## 실습

In [314]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

* 행삭제

In [315]:
# 서준 행 삭제

In [316]:
df.drop('서준')

수학  영어   음악  체육
우현  80  89   95  90
인아  70  95  100  90

In [317]:
# 서준, 우현 행 삭제

In [320]:
df.drop(['서준','우현'])

수학  영어   음악  체육
인아  70  95  100  90

* 열 삭제

In [321]:
#수학 열 삭제

In [339]:
df.drop('수학', axis=1)

영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [ ]:
#수학 영어 열 삭제

In [340]:
df.drop(['수학', '영어'], axis=1)

음악   체육
서준   85  100
우현   95   90
인아  100   90

* 행선택

In [353]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [354]:
#서준 행 선택 (라벨 색인, 정수색인)

In [362]:
df.iloc[0]
df.loc['서준']

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [356]:
# 서준 우현 행선택 (라벨색인, 정수색인, 슬라이싱)

In [364]:
df.loc['서준']
df.loc[['서준', '우현']]
df.iloc[[0, 2]]
df.iloc[0:2]

수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

* 열선택

In [365]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [366]:
#수학 열 선택

In [368]:
df.loc[:]['수학']

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

In [374]:
df.loc[:][['음악', '체육']]

음악   체육
서준   85  100
우현   95   90
인아  100   90

In [371]:
df['수학']
df[['음악', '체육']]

음악   체육
서준   85  100
우현   95   90
인아  100   90

* 원소 선택

In [377]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [381]:
# 서준의 음악점수

In [397]:
df.loc['서준']['음악']
df.iloc[0,2]

85

In [379]:
#서준의 음악 체육 점수

In [396]:
df.loc['서준'][['음악', '체육']]
df.iloc[0,[2, 3]]

음악     85
체육    100
Name: 서준, dtype: int64

In [380]:
# 서준 우현의 음체 점수

In [395]:
df.loc[['서준','우현']][['음악', '체육']]
df.iloc[[0,1],[2, 3]]

음악   체육
서준  85  100
우현  95   90

* 열 추가

In [398]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [399]:
# '국어' 열 추가, 값은 80점 지정

In [410]:
df['국어'] = [90, 80, 80]
df

수학  영어   음악   체육  국어
서준  90  98   85  100  90
우현  80  89   95   90  80
인아  70  95  100   90  80

* 행추가

In [401]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [411]:
# 본인 이름ㄴ 행추가 과목 점수 지정

In [429]:
df.loc['찬울'] = [10, 20, 30, 40]
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
찬울  10  20   30   40

In [430]:
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90
찬울  10  20   30   40

* 원소값변경

In [412]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
#서준의 체육점수 80점으로 변경(라벨 색인, 정수색인)

In [433]:
df.loc['서준', '체육'] = 80
df.iloc[0, 3]
df

수학  영어   음악  체육
서준  90  98   85  80
우현  80  89   95  90
인아  70  95  100  90
찬울  10  20   30  40

In [ ]:
#서준의 음악 체육 점수

In [436]:
df.loc['서준', ['음악', '체육']] = 80
df.iloc[0, 2:]
df

수학  영어   음악  체육
서준  90  98   80  80
우현  80  89   95  90
인아  70  95  100  90
찬울  10  20   30  40

In [437]:
# 국어 열 추가, 값은 80점 지정
df['국어'] = 80

# 본인 이름으로 행 추가
df.loc['재효'] = [90, 95, 80, 70, 75]

# 서준의 체육 점수를 80점으로 변경
df.loc['서준', '체육'] = 80

# 서준의 음악, 체육 점수 변경
df.loc['서준', ['음악', '체육']] = [90, 95]

# 과목이 행, 학생이 열
df.T


서준  우현   인아  찬울  재효
수학  90  80   70  10  90
영어  98  89   95  20  95
음악  90  95  100  30  80
체육  95  90   90  40  70
국어  80  80   80  80  75

In [438]:
exam_data = {'이름' : ['서준', '우현', '인아'],'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data)
df

이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [439]:
# 이름 열을 행 인덱스로 시정

In [441]:
df.set_index(['이름'], inplace=True)

In [442]:
df

수학  영어   음악   체육
이름                  
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

### reindex는 값이 없는 인덱스를 추가할 수 있다. set_index는 값이 다 있는걸 인덱스로 추가하는 것.

In [445]:
df.reindex(['인아', '서준', '찬울'])

수학    영어     음악     체육
이름                          
인아  70.0  95.0  100.0   90.0
서준  90.0  98.0   85.0  100.0
찬울   NaN   NaN    NaN    NaN

In [451]:
df

수학  영어   음악   체육
이름                  
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [452]:
# reset_index

In [455]:
df.reset_index() #설정하지 않았을 때처럼 01234의 인덱스가 된다. 적용하려면 inplace

이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

# 5. 산술 연산과 데이터 정렬

In [462]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a','c','d','e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a','c', 'e','f','g'])

In [463]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [464]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [465]:
s1 + s2 #a c e는 둘 다 값이 있다. 하나에만 있으면 NaN으로 나옴 한쪽값만 나오는게 아니라 NaN+n이런 느낌이라 그런 드 

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [466]:
df1 = pd.DataFrame({'A' : [1, 2]})
df2 = pd.DataFrame({'b' : [3, 4]})

In [467]:
df1

A
0  1
1  2

In [468]:
df2

b
0  3
1  4

In [472]:
df1 - df2 #index 기준이 아닌듯 주어진 컬럼도 같아야하고 인덱스도 같아야하는 기준인듯

A   b
0 NaN NaN
1 NaN NaN

In [513]:
df1 = pd.DataFrame(np.arange(12).reshape(3,4), columns = ['a', 'b', 'c', 'd']) # list('abcd')도 된다

df2 = pd.DataFrame(np.arange(20).reshape(4,5), columns = list('abcde')) # list('abcd')도 된다
df2.loc[1,'b'] = np.nan

In [514]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [515]:
df2

a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19

In [516]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [517]:
df1.add(df2, fill_value=0) #없는 애들이 0이라고 되기에 Nan이 아니라 DF2에 있는 값들이 살아있어짐

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [481]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [482]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [518]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [483]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [487]:
df1.reindex(columns=df2.columns, fill_value=0, index= df2.index) #fill_value는 NaN 을 채워준다.

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0
3  0  0   0   0  0

In [489]:
1 / df1 == df1.rdiv(1)

a     b     c     d
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True

* (참고) 넘파이 산술연산 예

In [491]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [492]:
arr[0]

array([0., 1., 2., 3.])

In [493]:
arr * 2

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.]])

In [494]:
arr - arr[0] #한 행은 시리즈형태니까 이를 이용해서 행마다 모두 계산

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

* 데이터 프라임 산술연산 예

In [507]:
frame = pd.DataFrame(np.arange(12.).reshape(4, 3),
             columns = list('bde'),
             index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [508]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [509]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [510]:
series2 = pd.Series(range(3), index = ['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [511]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [512]:
frame + series2 #frame하고 series의 계산이 가능하다.

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [520]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [521]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [522]:
frame - series3

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [524]:
frame.sub(series3, axis=0) #함수를 굳이 쓰는 이유는 함수는 설정들이 많아서 편하다. axis는 ㅇ적용할 축의 번호

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [526]:
frame.sub(series3, axis='index')
(frame.T - series3).T

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## 실습

In [527]:
student1 = pd.Series({'국어':100, '영어':80, '수학':90})
student1

국어    100
영어     80
수학     90
dtype: int64

In [534]:
# 과목별 점수를 100으로 나눈다.
student1/100
student1.div(100)

국어    1.0
영어    0.8
수학    0.9
dtype: float64

In [535]:
student1 = pd.Series({'국어':100, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90, '영어':80})

In [544]:
(student1+student2)/ 2
student1.add(student2).div(2)

국어    True
수학    True
영어    True
dtype: bool

In [546]:
student1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90})

In [549]:
student1.add(student2, fill_value=0).div(2)

국어    45.0
수학    85.0
영어    40.0
dtype: float64