In [1]:
import numpy as np
import pandas as pd

# 데이터 준비하기 : 조인, 병합, 변형

## 1. 계층적 색인

In [3]:
data = pd.Series(np.random.randn(9),
                 index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                        [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

a  1    0.882760
   2   -1.354899
   3    0.184977
b  1    0.775003
   3    2.787558
c  1   -0.134351
   2    0.650272
d  2   -1.156505
   3   -0.596873
dtype: float64

In [5]:
data.index #다중인덱스!

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [6]:
data['b'] 

1    0.775003
3    2.787558
dtype: float64

In [7]:
data['b':'c'] #단일 인덱스면 하나씩만 가져오는데 다중인덱스라 b랑 c에 포함된 애들 다 나와서 4개다.

b  1    0.775003
   3    2.787558
c  1   -0.134351
   2    0.650272
dtype: float64

In [8]:
data.loc[:, 2] # 인덱스 중에서 2에 해당하는 값 가져오기

a   -1.354899
c    0.650272
d   -1.156505
dtype: float64

In [11]:
data.loc['a']

1    0.882760
2   -1.354899
3    0.184977
dtype: float64

In [12]:
data

a  1    0.882760
   2   -1.354899
   3    0.184977
b  1    0.775003
   3    2.787558
c  1   -0.134351
   2    0.650272
d  2   -1.156505
   3   -0.596873
dtype: float64

In [15]:
data.unstack() #다중인덱스의 2번째 인덱스를 컬럼으로 받기

1         2         3
a  0.882760 -1.354899  0.184977
b  0.775003       NaN  2.787558
c -0.134351  0.650272       NaN
d       NaN -1.156505 -0.596873

In [17]:
data.unstack().stack() #되돌리기

a  1    0.882760
   2   -1.354899
   3    0.184977
b  1    0.775003
   3    2.787558
c  1   -0.134351
   2    0.650272
d  2   -1.156505
   3   -0.596873
dtype: float64

* 컬럼도 위와 같이 할 수 있다.

In [19]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                     columns=[['Ohio', 'Ohio', 'Colorado'],
                              ['Green', 'Red', 'Green']])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [21]:
frame.index.names = ['key1', 'key2'] #인덱스가 두개라서 이렇게 지정.
frame

Ohio     Colorado
          Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [23]:
frame.columns.names = ['state', 'color']
frame #이런 식으로 key1과 key2는 인덱스네임 state와 color은 컬럼 네임이다.

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [24]:
frame['Ohio'] #하위 컬럼인 green과 red가 딸려옴.

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

### 1.1 계층의 순서를 바꾸고 정렬하기

In [25]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [26]:
frame.swaplevel('key1', 'key2') #서브와 메인을 바꿈.

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [27]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [28]:
frame.sort_index(level=1) #이런식으로 정렬가능 2번째 기준으로

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [29]:
frame.swaplevel(0, 1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

### 1.2 계층별 요약 통계

In [30]:
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [32]:
frame.sum(level='key2') #같은 key2의 인덱스끼리 더하기 a와 b를 더하므로 a랑 b의 경계가 사라져서 key2만 남은 듯

state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [33]:
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1),
                      'c': ['one', 'one', 'one', 'two', 'two',
                            'two', 'two'],
                      'd': [0, 1, 2, 0, 1, 2, 3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [35]:
frame2 = frame.set_index(['c', 'd']) #두개를 set_index하면 다중인덱스!
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [36]:
frame2.reset_index() #인덱스가 열로 돌아간다 허나 순서가 cd순으로 인덱스여서 cd ab로 열이 정렬된다.

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [37]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

## 2. 데이터 합치기

### 2.1 데이터베이스 스타일로 DataFrame 합치기

In [38]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                    'data2': range(3)})

In [39]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [40]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [42]:
pd.merge(df1, df2) #둘이 합쳐진다. 둘 모두에 존재하는 애들만 merge한다. 디폴트가 이너라서임 아우터로 바꾸면 되긴 함

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [43]:
pd.merge(df1, df2, on = 'key') #on으로 중심을 정할 수 있는데 없어도 중복되는 열이 있으면 해당 열로 하는 듯.

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [46]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'], 'data1': range(7)})
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'], 'data2': range(3)})

In [47]:
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [48]:
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [51]:
pd.merge(df3, df4, left_on = 'lkey', right_on = 'rkey') #있는 것들을 늘려서 해줌.

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [52]:
pd.merge(df1, df2, how='outer') #아까 말했듯 디폴트는 이너라서 아우터로 바꾸면 양쪽에 있는 모든 값에 대해 나타낸다.

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

### 2.2 색인 병합하기

In [54]:
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'], 'value': range(6)})
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])

In [55]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [56]:
right1

group_val
a        3.5
b        7.0

In [58]:
pd.merge(left1, right1, left_on = 'key', right_index = True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [63]:
pd.merge(left1, right1, left_on = 'key', right_index = True, how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [59]:
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                     index=['a', 'c', 'e'],
                     columns=['Ohio', 'Nevada'])
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                      index=['b', 'c', 'd', 'e'],
                      columns=['Missouri', 'Alabama'])

In [60]:
left2

Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [61]:
right2

Missouri  Alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [65]:
pd.merge(left2, right2, left_index=True, right_index=True) #두개 다 갖고 있는 c e에 대해서 가져옴

Ohio  Nevada  Missouri  Alabama
c   3.0     4.0       9.0     10.0
e   5.0     6.0      13.0     14.0

In [67]:
left2.join(right2) #기준이 left라서 left에 있는 것은 꼭 들어간다. left의 인덱스 ace가 기준이라서 ace가 무조건 들어감.

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
c   3.0     4.0       9.0     10.0
e   5.0     6.0      13.0     14.0

In [69]:
right2.join(left2) #위와 같아서 bcde는 무조건

Missouri  Alabama  Ohio  Nevada
b       7.0      8.0   NaN     NaN
c       9.0     10.0   3.0     4.0
d      11.0     12.0   NaN     NaN
e      13.0     14.0   5.0     6.0

In [71]:
left2.join(right2, how='inner') # 이너 옵션을 주면 인덱스의 교집합만 가져옴

Ohio  Nevada  Missouri  Alabama
c   3.0     4.0       9.0     10.0
e   5.0     6.0      13.0     14.0

In [73]:
left2.join(right2, how='outer') #아우터 옵션은 합집합의 인덱스

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [74]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [75]:
right1

group_val
a        3.5
b        7.0

In [76]:
left1.join(right1) #이러면 left1기준이라서

key  value  group_val
0   a      0        NaN
1   b      1        NaN
2   a      2        NaN
3   a      3        NaN
4   b      4        NaN
5   c      5        NaN

In [77]:
left1.join(right1, on = 'key') #key를 기준으로 join한다. 

key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

### 2.3 축 따라 이어 붙이기

In [79]:
arr = np.arange(12).reshape((3, 4))

In [80]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.concatenate(arr, arr) #축을 따라서 이어붙이기 디폴트 axis = 0 행축을 기준으로 추가 행이 생긴 거처럼 이어붙이기 axis가 1이라면 열축을 기준으로  옆으로 붙는다.

In [85]:
np.concatenate([arr, arr], axis=0) # axis는 디폴트 0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [87]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])

In [88]:
s1

a    0
b    1
dtype: int64

In [89]:
s2

c    2
d    3
e    4
dtype: int64

In [90]:
s3

f    5
g    6
dtype: int64

In [94]:
pd.concat([s1, s2, s3]) #시리즈는 concat이다.

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [96]:
pd.concat([s1, s2, s3], axis = 1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [98]:
s4 = pd.concat([s1, s3])
s4

a    0
b    1
f    5
g    6
dtype: int64

In [99]:
pd.concat([s1, s4], axis=1)

0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [101]:
pd.concat([s1, s4], axis=1, join='inner') #디폴트는 아우터

0  1
a  0  0
b  1  1

In [103]:
pd.concat([s1, s2, s3]) #어디서 어디까지가 s1이고 s2고 s3인것을 모른다 장점이지만 어디서 왔는지를 알 필요도 있다.

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [107]:
result = pd.concat([s1, s2, s3], keys = ['one', 'two', 'three']) #각각에대해 키값 부여가능
result

one    a    0
       b    1
two    c    2
       d    3
       e    4
three  f    5
       g    6
dtype: int64

In [109]:
result.unstack() #one은 a b, two는 c d e three는 f g를 갖고 있던 것을 알 수 있다. 

a    b    c    d    e    f    g
one    0.0  1.0  NaN  NaN  NaN  NaN  NaN
two    NaN  NaN  2.0  3.0  4.0  NaN  NaN
three  NaN  NaN  NaN  NaN  NaN  5.0  6.0

In [110]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],
                   columns=['one', 'two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],
                   columns=['three', 'four'])

In [111]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [112]:
df2

three  four
a      5     6
c      7     8

In [117]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2']) #다중 컬럼으로 알아볼 수 있다. 없는 애들도 나오는 합집합느낌

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [118]:
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])

In [119]:
df1

a         b         c         d
0  1.174832  0.260438  0.726275 -0.584534
1  0.097695  0.512099  0.707117  0.353290
2 -0.963531  1.312356 -0.309643 -1.429487

In [120]:
df2

b         d         a
0  0.305725  0.538256 -1.296003
1 -1.605361 -0.187548  1.503875

In [122]:
pd.concat([df1, df2])

a         b         c         d
0  1.174832  0.260438  0.726275 -0.584534
1  0.097695  0.512099  0.707117  0.353290
2 -0.963531  1.312356 -0.309643 -1.429487
0 -1.296003  0.305725       NaN  0.538256
1  1.503875 -1.605361       NaN -0.187548

In [123]:
pd.concat([df1, df2], ignore_index=True) #인덱스가 겹치면 똑같은 이름의 인덱스로 되므로 기존ㅇ 인덱스를 무시함. 

a         b         c         d
0  1.174832  0.260438  0.726275 -0.584534
1  0.097695  0.512099  0.707117  0.353290
2 -0.963531  1.312356 -0.309643 -1.429487
3 -1.296003  0.305725       NaN  0.538256
4  1.503875 -1.605361       NaN -0.187548

* 그룹 연산